/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stargazerTokenSol from "./StargazerToken.sol";
export type { stargazerTokenSol };
export type { StargazerGreeter } from "./StargazerGreeter";
