/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stargazerTokenSol from "./StargazerToken.sol";
export { StargazerGreeter__factory } from "./StargazerGreeter__factory";
